steps:
  # RecordedVoice (Create)
  - name: &docker 'docker.io/library/python:3.7'
    entrypoint: /bin/sh
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/recorded/id/get'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'recorded-voice-create', '--trigger-http', '--runtime=python37', '--entry-point=recorded_voice_create']
    dir: 'functions/recorded/create'

  # RecordedVoice (GetAll)
  - name: *docker
    entrypoint: /bin/sh
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/recorded/all'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'recorded-voice-get-all', '--trigger-http', '--runtime=python37', '--entry-point=recorded_voice_get_all']
    dir: 'functions/recorded/all'

  # RecordedVoice (id/Get)
  - name: *docker
    entrypoint: /bin/sh
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/recorded/id/get'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'recorded-voice-get', '--trigger-http', '--runtime=python37', '--entry-point=recorded_voice_get']
    dir: 'functions/recorded/id/get'

  # RecordedVoice (id/Update)
  - name: *docker
    entrypoint: /bin/sh
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/recorded/id/get'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'recorded-voice-update', '--trigger-http', '--runtime=python37', '--entry-point=recorded_voice_update']
    dir: 'functions/recorded/id/update'

  # RecordedVoice (id/Delete)
  - name: *docker
    entrypoint: /bin/sh
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/recorded/id/get'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'recorded-voice-delete', '--trigger-http', '--runtime=python37', '--entry-point=recorded_voice_delete']
    dir: 'functions/recorded/id/delete'
